### ISSUE TITLE
You should add your project to #CodeAgainstCoronavirus

### ISSUE THREAD

**Issue by NotMoni** [yohix/corona#11]
Check it out:
https://github.com/NotMoni/code-against-coronavirus

Spread the Message
#CodeAgainstCoronavirus.

**Comment by yohix** [comment]
:pray: Thanks, @NotMoni,

Please add it!

I'm so lazy to create a pull request! :face_with_thermometer: 

![](https://media0.giphy.com/media/pVkmGyqYRt4qY/giphy.gif)

**Comment by NotMoni** [comment]
@yohix I want to. But It would mean a lot if you could add it since it's your project.

**Comment by NotMoni** [comment]
Could you also promote the awareness in your README.md?

**Comment by yohix** [comment]
Ok, @NotMoni I will add it today evening **IST**!

![](https://media2.giphy.com/media/a3zqvrH40Cdhu/giphy.gif)

**Comment by NotMoni** [comment]
Thanks Man. Mean a lot to me.

**Comment by NotMoni** [comment]
@yohix Thanks :D

**Comment by NotMoni** [comment]
@yohix Can you add me on discord Moni#1410

**Comment by yohix** [comment]
Sure @NotMoni

**Comment by yohix** [comment]
@NotMoni Not working!

![screenshot](https://user-images.githubusercontent.com/61746440/77839794-c066fb00-719d-11ea-93cc-c459830fe158.png)

PS: I will close this Issue after PR gets merged :smiley_cat:

**Comment by yohix** [comment]
And @NotMoni 

`Write a piece of code that prints "Code Against Coronavirus" (in any language you wish).`

Where do I write it?

**Comment by NotMoni** [comment]
oh
its 
```M O N I#1410```

**Comment by NotMoni** [comment]
My bad broooo

**Comment by NotMoni** [comment]
@yohix
